version: "3"

services:
  strapi:
    image: node:18-alpine
    ports:
      - "1337:1337"
    environment:
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      NODE_ENV: development
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn develop"
    depends_on:
      - db
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/data/postgres
    logging:
      driver: none

volumes:
  postgresdata:
  node_modules:
